name: Sync Content to Lark

on:
  schedule:
    # Chạy mỗi ngày lúc 00:00 UTC = 7:00 AM giờ Việt Nam
    - cron: '0 0 * * *'
  
  # Cho phép chạy thủ công từ GitHub UI
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run sync script
      run: python get_content_fb.py